# 切记保存为UTF-8类型.
spring:
  profiles:
    active:
    - dev # 开发环境

---
spring:
  profiles: dev # 开发环境
  application:
    name: microservicecloud-config-3344-dev

---
spring:
  profiles: test # 测试环境
  application:
    name: microservicecloud-config-3344-test